from docx import Document
from docx.shared import Inches 
import pyttsx3

def speak(text):
    pyttsx3.speak(text)

document = Document()

# profile picture
document.add_picture(
    'cv-image.png',
    width=Inches(2.0) 
    )

#name phone and email details 

speak('Welcome to Gerald CV builder')
speak('Please state your name')
name = input('What is your name:\n')
speak('Hello ' + name + ' how are you today?')

speak('Please we would like you to share your phone number')
phone_number = input('Please type in your phone number:\n')

speak('Enter a valid email address')
email = input('Enter your email address:\n')

document.add_paragraph(
    name + ' | ' + phone_number + ' | ' + email
)

#About me 
speak('Tell us about yourself and your career')
document.add_heading('About Me')
document.add_paragraph(
    input('Talk about yoursalf?:\n')
)

#work Experience
speak('Share your work experience')
document.add_heading('Work Experience')
p = document.add_paragraph()

company = input('Enter Company name;\n')
from_date = input('Started date;\n')
till_date = input('Till date; \n')

p.add_run(company + ' ').bold = True
p.add_run(from_date + ' ' + 'to' + ' ' + till_date + '\n').italic = True

experience_details = input(
    'Describe your experience at \n' + company
)
p.add_run(experience_details)

#More experirnces 
while True:
    has_more_experiences = input(
        'Do you have more experiences? Yes or NO \n')
    if has_more_experiences.lower() == 'yes':
        p = document.add_paragraph()

        company = input('Enter Company name;\n')
        from_date = input('Started date;\n')
        till_date = input('Till date; \n')

        p.add_run(company + ' ').bold = True
        p.add_run(from_date + '--' + till_date + '\n').italic = True

        experience_details = input(
            'Describe your experience at \n' + company
        )
        p.add_run(experience_details)
    else:
        break

# Skill Set 
speak('What skill set do you have?')
document.add_heading('Skill Set')
skills = input('Enter Skill Sets \n')
p = document.add_paragraph()
p.style = 'List Bullet'

#More Skill Set
while True:
    has_more_skills = input('Do you have more skill sets? Yes or No \n')
    if has_more_skills.lower() == 'yes':
        skills = input('Enter Skill Sets \n')
        p = document.add_paragraph()
        p.style = 'List Bullet'
    else:
        break

#Education and Certifications 
speak('Share your educational background and certification')
document.add_heading('Education and Certifications')
p = document.add_paragraph()

education_and_certification = input('Enter your education and certification: \n')
start_date = input('Start Date: \n')
end_date = input('End Date: \n')

p.add_run(education_and_certification + ' ').bold =True
p.add_run(start_date  + '---' + end_date + '\n').italic = True

certification_details = input(
    'Describe the skill set acquired from the certification: \n'
)
p.add_run (certification_details)


#More Education and Certifications 
while True:
    has_more_certifications = input(
        'Do you have more certification/Education? Yes or NO: \n')
    if has_more_certifications.lower() == 'yes':
        p = document.add_paragraph()

        education_and_certification = input('Enter your education and certification: \n')
        start_date = input('Start Date: \n')
        end_date = input('End Date: \n')

        p.add_run(education_and_certification + ' ').bold =True
        p.add_run(start_date  + '---' + end_date + '\n').italic = True

        certification_details = input(
            'Describe the skill set acquired from the certification: \n'
        )
        p.add_run (certification_details)
        p.style = 'List Bullet'
    else:
        break 

speak('Thank you' + name + "for using Gerald CV builder")

#Footer 
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = 'CV Builder Generated by Gerald Obasi'



document.save('cv.docx')